version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: portfolio-tracker-backend
    ports:
      - "5001:5001"
    volumes:
      - ./backend/portfolio.db:/app/portfolio.db
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: portfolio-tracker-frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    restart: unless-stopped